/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./SgGov.types";
import * as _1 from "./SgGov.client";
import * as _2 from "./SgGov.message-composer";
import * as _3 from "./SgNftGroup.types";
import * as _4 from "./SgNftGroup.client";
import * as _5 from "./SgNftGroup.message-composer";
export namespace contracts {
  export const SgGov = { ..._0,
    ..._1,
    ..._2
  };
  export const SgNftGroup = { ..._3,
    ..._4,
    ..._5
  };
}