/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.20.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./DaoGovernance.types";
import * as _1 from "./DaoGovernance.client";
import * as _2 from "./DaoGovernance.message-composer";
export namespace contracts {
  export const DaoGovernance = { ..._0,
    ..._1,
    ..._2
  };
}