/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Admin = {
  address: {
    addr: string;
  };
} | {
  creator: {};
};
export type Binary = string;
export interface InstantiateMsg {
  collection: string;
  cw721_init_msg: ContractInstantiateMsg;
}
export interface ContractInstantiateMsg {
  admin?: Admin | null;
  code_id: number;
  label: string;
  msg: Binary;
}
export type ExecuteMsg = {
  receive_nft: Cw721ReceiveMsg;
} | {
  remove: {
    token_id: string;
  };
};
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
}
export type QueryMsg = {
  collection: {};
} | {
  total_weight: {};
} | {
  list_members: {
    limit?: number | null;
    start_after?: string | null;
  };
} | {
  member: {
    addr: string;
    at_height?: number | null;
  };
};
export type String = string;
export interface MemberListResponse {
  members: Member[];
}
export interface Member {
  addr: string;
  weight: number;
}
export interface MemberResponse {
  weight?: number | null;
}
export interface TotalWeightResponse {
  weight: number;
}